name: "Continuous Integration Workflow"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Server Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        working-directory: ./server
        run: npm install
      
      - name: Run All Node.js Tests
      working-directory: ./server
        run: npm run test