apiVersion: apps/v1
kind: Deployment
metadata:
  name: artist-info
spec:
  replicas: 3
  selector:
    matchLabels:
      app: artist-info
  template:
    metadata:
      labels:
        app: artist-info
    spec:
      containers:
        - name: artist-info
          image: isabellachen3988/artist-info:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---

apiVersion: v1 # deployment service configurations
kind: Service
metadata:
  name: artist-info
spec:
  type: NodePort
  selector:
    app: artist-info
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 30000